<div class="alt-bg-section">
    <?php include __DIR__ . '/menu.phtml' ?>
    <div class="container">

    <?php if (isset($reservation['tourCheckInTime'])): ?>
    <div class="alert alert-info text-center mt-3" role="alert">
        Party is checked in for the <strong><?= $reservation['assignedTour'] ?></strong> tour.
    </div>
    <? endif ?>
    <?php if (isset($reservation['launchCheckInTime'])): ?>
    <div class="alert alert-info text-center mt-3" role="alert">
        Party is checked in for launch!
    </div>
    <? endif ?>

        <h1>Check-In: <?= $id ?></h1>
        <strong>Reservation time (UTC):</strong> <?= $reservationTime ?>
        <?php if (isset($reservation['assignedBoat'])): ?>
            <br><strong>Boat assignment:</strong> <?= $reservation['assignedBoat'] ?>
        <?php endif ?>
        <?php if (isset($reservation['assignedTour'])): ?>
            <br><strong>Tour assignment:</strong> <?= $reservation['assignedTour'] ?>
        <?php endif ?>

<div class="text-center">
<a href="/admin/resend-confirmation/<?= $id ?>" onclick="return confirm('Are you sure?')">Resend Confirmation</a><br>
<a href="/reservation/<?= $id ?>">Reservation Link</a><br>
</div>

    <fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Party &amp; Contact</legend></fieldset>
    <form action="/admin/reservation/<?= $id ?>" method="post" class="container justify-content-center" id="party-contact-form">

    <div class="form-group form-row justify-content-center">
        <label for="reservation-name" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Name for Reservation:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <input value="<?= $reservation['reservationName'] ?>" type="text" id="reservation-name" name="reservationName" class="form-control form-control-lg" aria-describedby="reservation-name-hint" required>
            <span id="reservation-name-hint" class="form-text text-center">First, full, or group/party name.</span>
        </div>
    </div>

    <div class="form-group form-row justify-content-center">
        <label for="reservation-email" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Email Address:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
        <input value="<?= $reservation['reservationEmail'] ?>" type="email" id="reservation-email" name="reservationEmail" class="form-control form-control-lg" aria-describedby="reservation-email-hint" required>
            <span id="reservation-email-hint" class="form-text text-center">Confirmation will be sent here.</span>
        </div>
    </div>
    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <button class="button btn btn-warning float-right btn-lg" type="submit">Update Party Information &raquo;</button><br>
        </div>
    </div>
    </form>

    <fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Reservation Details</legend></fieldset>

    <div class="row">
        <div class="col-lg-8">
            <table class="table table-dark">
              <thead>
                <tr>
                  <th scope="col">Description</th>
                  <th scope="col" class="text-right">Price</th>
                  <th scope="col" class="text-right">Qty</th>
                  <th scope="col" class="text-right">Total</th>
                </tr>
              <thead>
              <tbody>
                <?php if ($reservation['upperQty'] > 0): ?>
                <tr>
                  <td>Upper Deck Launch Ticket</td>
                  <td class="text-right">$<?= number_format($reservation['upperPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['upperQty'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['upperPrice'] * $reservation['upperQty'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['standardQty'] > 0): ?>
                <tr>
                  <td>Standard Launch Ticket<br><small>(Boat preference: <?= strtoupper($reservation['boatPref1']); ?>)</small></td>
                  <td class="text-right">$<?= number_format($reservation['standardPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['standardQty'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['standardPrice'] * $reservation['standardQty'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['privateQty'] > 0): ?>
                <tr>
                  <td>Private Boat Launch Ticket</td>
                  <td class="text-right">$<?= number_format($reservation['privatePrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['privateQty'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['privatePrice'] * $reservation['privateQty'],2) ?></td>
                </tr>
                <?php endif; ?>

                <?php if ($reservation['tourQty'] > 0): ?>
                <tr>
                  <td>Pre-Launch Tour<br><small>(8:30am - <?= $reservation['tourPref1'] == 'none' ? 'n/a' : $reservation['tourPref1'] . ' choice' ?>; 12:30pm - <?= $reservation['tourPref2'] == 'none' ? 'N/A' : $reservation['tourPref2'] . ' choice' ?>)</small></td>
                  <td class="text-right">$<?= number_format($reservation['tourPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['tourQty'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['tourPrice'] * $reservation['tourQty'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['shirtQtySm'] > 0): ?>
                <tr>
                  <td>Mission T-Shirt (Small)</td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['shirtQtySm'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'] * $reservation['shirtQtySm'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['shirtQtyMd'] > 0): ?>
                <tr>
                  <td>Mission T-Shirt (Medium)</td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['shirtQtyMd'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'] * $reservation['shirtQtyMd'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['shirtQtyLg'] > 0): ?>
                <tr>
                  <td>Mission T-Shirt (Large)</td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['shirtQtyLg'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'] * $reservation['shirtQtyLg'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['shirtQtyXl'] > 0): ?>
                <tr>
                  <td>Mission T-Shirt (XL)</td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['shirtQtyXl'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'] * $reservation['shirtQtyXl'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['shirtQty2xl'] > 0): ?>
                <tr>
                  <td>Mission T-Shirt (2XL)</td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['shirtQty2xl'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'] * $reservation['shirtQty2xl'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['shirtQty3xl'] > 0): ?>
                <tr>
                  <td>Mission T-Shirt (3XL)</td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['shirtQty3xl'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'] * $reservation['shirtQty3xl'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['cookieQty'] > 0): ?>
                <tr>
                  <td>Traditional Launch Day Cookie</td>
                  <td class="text-right">$<?= number_format($reservation['cookiePrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['cookieQty'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['cookiePrice'] * $reservation['cookieQty'],2) ?></td>
                </tr>
                <?php endif; ?>
              </tbody>
            </table>
        </div><!--/col-->
        <div class="col-lg-4">
            <table class="table table-dark table-borderless">
              <thead>
                <tr>
                  <th scope="col">Subtotal</th>
                  <td scope="col" class="text-right">$<?= number_format($reservation['subTotal'],2) ?></td>
                </tr>
              <thead>
              <tbody>
                <?php if ($reservation['tourDiscountQty'] > 0): ?>
                <tr>
                  <td>Tour + Launch Discount</td>
                  <td class="text-right">-$<?= number_format($reservation['tourDiscountValue'] * $reservation['tourDiscountQty'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if (isset($reservation['discountCode'])): ?>
                <tr>
                  <td>Discount Code "<?= $reservation['discountCode'] ?>"</td>
                  <td class="text-right">-$<?= number_format($reservation['discountCodeAmount'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['donation'] > 0): ?>
                <tr>
                  <td>Donation</td>
                  <td class="text-right">$<?= number_format($reservation['donation'],2) ?></td>
                </tr>
                <?php endif; ?>
                <tr class="border-top border-secondary">
                  <th scope="col">Total Paid</th>
                  <td class="text-right">$<?= number_format($reservation['totalPaymentDue'],2) ?></td>
                </tr>
              </tbody>
            </table>
        </div> <!--/col-->
    </div> <!--/row-->

    <?php if ($reservation['standardQty'] > 0 || $reservation['privateQty'] > 0 || $reservation['upperQty']): ?>
    <fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Launch Check-In</legend></fieldset>
    <form action="/admin/reservation/<?= $id ?>" method="post" class="container justify-content-center" id="launch-checkin-form">
    <div class="form-group form-row justify-content-center">
        <div class="col-9 col-sm-12 col-md-10 col-lg-8">
            <label for="tour-check-in-notes" class="form-label font-weight-bold">Launch Check-In Notes:</label>
            <textarea class="form-control" id="launch-check-in-notes" name="launchCheckInNotes"><?php if (isset($reservation['launchCheckInNotes'])): ?><?= $reservation['launchCheckInNotes'] ?><?php endif ?></textarea>
        </div>
    </div>
    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <input type="hidden" name="launchCheckInTime" value="<?= time() ?>">
            <button class="button btn btn-warning float-right btn-lg" type="submit">Check Party In &raquo;</button><br>
        </div>
    </div>
    </form>
    <?php endif ?>

    <?php if ($reservation['tourQty'] > 0): ?>
    <fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Tour Check-In</legend></fieldset>
    <form action="/admin/reservation/<?= $id ?>" method="post" class="container justify-content-center" id="tour-checkin-form">
    <div class="form-group form-row justify-content-center">
        <div class="col-9 col-sm-12 col-md-10 col-lg-8">
            <label for="tour-check-in-notes" class="form-label font-weight-bold">Tour Check-In Notes:</label>
            <textarea class="form-control" id="tour-check-in-notes" name="tourCheckInNotes"><?php if (isset($reservation['tourCheckInNotes'])): ?><?= $reservation['tourCheckInNotes'] ?><?php endif ?></textarea>
        </div>
    </div>
    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <input type="hidden" name="launchCheckInTime" value="<?= time() ?>">
            <button class="button btn btn-warning float-right btn-lg" type="submit">Check Party In &raquo;</button><br>
        </div>
    </div>
    </form>

    <fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Update Tour Prefs</legend></fieldset>
    <form action="/admin/reservation/<?= $id ?>" method="post" class="container justify-content-center" id="tour-pref-form">
    <div class="form-group form-row justify-content-center">
        <label for="standard-qtyss" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Tour Preference:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="form-group input-group input-group-sm">
                <div class="input-group-prepend">
                    <div class="input-group-text text-monospace">8:30am-12:30pm</div>
                </div>
                <select id="tour-pref-1" name="tourPref1" class="form-control">
                    <option value="">Choose:</option>
                    <option value="first" <?php if(isset($reservation['tourPref1']) && $reservation['tourPref1'] == 'first'): ?>selected<?php endif ?>>1st choice</option>
                    <option value="second" <?php if(isset($reservation['tourPref1']) && $reservation['tourPref1'] == 'second'): ?>selected<?php endif ?>>2nd choice</option>
                    <option value="third" <?php if(isset($reservation['tourPref1']) && $reservation['tourPref1'] == 'third'): ?>selected<?php endif ?>>3rd choice</option>
                    <option value="none" <?php if(isset($reservation['tourPref1']) && $reservation['tourPref1'] == 'none'): ?>selected<?php endif ?>>Unavailable</option>
                </select>
            </div>
            <div class="form-group input-group input-group-sm">
                <div class="input-group-prepend">
                    <div class="input-group-text text-monospace">12:30pm-4:30pm</div>
                </div>
                <select id="tour-pref-2" name="tourPref2" class="form-control">
                    <option value="first" <?php if(isset($reservation['tourPref2']) && $reservation['tourPref2'] == 'first'): ?>selected<?php endif ?>>1st choice</option>
                    <option value="second" <?php if(isset($reservation['tourPref2']) && $reservation['tourPref2'] == 'second'): ?>selected<?php endif ?>>2nd choice</option>
                    <option value="third" <?php if(isset($reservation['tourPref2']) && $reservation['tourPref2'] == 'third'): ?>selected<?php endif ?>>3rd choice</option>
                    <option value="none" <?php if(isset($reservation['tourPref2']) && $reservation['tourPref2'] == 'none'): ?>selected<?php endif ?>>Unavailable</option>
                </select>
            </div>
            <?php if(isset($reservation['tourPref3'])): ?>
            <div class="form-group input-group input-group-sm">
                <div class="input-group-prepend">
                    <div class="input-group-text text-monospace">&nbsp;3pm-6:30pm</div>
                </div>
                <select id="tour-pref-3" name="tourPref3" class="form-control">
                    <option value="first" <?php if(isset($reservation['tourPref3']) && $reservation['tourPref3'] == 'first'): ?>selected<?php endif ?>>1st choice</option>
                    <option value="second" <?php if(isset($reservation['tourPref3']) && $reservation['tourPref3'] == 'second'): ?>selected<?php endif ?>>2nd choice</option>
                    <option value="third" <?php if(isset($reservation['tourPref3']) && $reservation['tourPref3'] == 'third'): ?>selected<?php endif ?>>3rd choice</option>
                    <option value="none" <?php if(isset($reservation['tourPref3']) && $reservation['tourPref3'] == 'none'): ?>selected<?php endif ?>>Unavailable</option>
                </select>
            </div>
            <?php endif ?>
            <!--<span id="standard-qty-hint" class="form-text">We'll do our best to get your party on the preferred boat.</span>-->
        </div>
    </div>
    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <button class="button btn btn-warning float-right btn-lg" type="submit">Update Tour Preferences &raquo;</button><br>
        </div>
    </div>
    </form>
    <?php endif ?>

    <?php if ($reservation['standardQty'] > 0 || $reservation['privateQty'] > 0 || $reservation['upperQty']): ?>
    <fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Update Boat Prefs</legend></fieldset>
    <form action="/admin/reservation/<?= $id ?>" method="post" class="container justify-content-center" id="tour-pref-form">

    <div class="form-group form-row justify-content-center">
        <label for="boat-pref-1" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Boat Preference:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="form-group input-group input-group-sm">
                <div class="input-group-prepend">
                    <div class="input-group-text text-monospace font-weight-bold">1st </div>
                </div>
                <select id="boat-pref-1" name="boatPref1" class="form-control admin-boat-preferences">
                    <option value="none" <?php if(isset($reservation['boatPref1']) && $reservation['boatPref1'] == 'none'): ?>selected<?php endif ?>>No preference</option>
                    <option value="oo2-upper" <?php if(isset($reservation['boatPref1']) && $reservation['boatPref1'] == 'oo2-upper'): ?>selected<?php endif ?>>OO2 Upper Deck (Ocean)</option>
                    <option value="oo2" <?php if(isset($reservation['boatPref1']) && $reservation['boatPref1'] == 'oo2'): ?>selected<?php endif ?>>OO2 Lower Deck (Ocean)</option>
                    <option value="tnt1" <?php if(isset($reservation['boatPref1']) && $reservation['boatPref1'] == 'tnt1'): ?>selected<?php endif ?>>TNT1 (Ocean)</option>
                    <option value="tnt2" <?php if(isset($reservation['boatPref1']) && $reservation['boatPref1'] == 'tnt2'): ?>selected<?php endif ?>>TNT2 (River)</option>
                </select>
            </div>
            <div class="form-group input-group input-group-sm">
                <div class="input-group-prepend">
                    <div class="input-group-text text-monospace font-weight-bold">2nd </div>
                </div>
                <select id="boat-pref-2" name="boatPref2" class="form-control admin-boat-preferences">
                    <option value="none" <?php if(isset($reservation['boatPref2']) && $reservation['boatPref2'] == 'none'): ?>selected<?php endif ?>>No preference</option>
                    <option value="oo2-upper" <?php if(isset($reservation['boatPref2']) && $reservation['boatPref2'] == 'oo2-upper'): ?>selected<?php endif ?>>OO2 Upper Deck (Ocean)</option>
                    <option value="oo2" <?php if(isset($reservation['boatPref2']) && $reservation['boatPref2'] == 'oo2'): ?>selected<?php endif ?>>OO2 Lower Deck (Ocean)</option>
                    <option value="tnt1" <?php if(isset($reservation['boatPref2']) && $reservation['boatPref2'] == 'tnt1'): ?>selected<?php endif ?>>TNT1 (Ocean)</option>
                    <option value="tnt2" <?php if(isset($reservation['boatPref2']) && $reservation['boatPref2'] == 'tnt2'): ?>selected<?php endif ?>>TNT2 (River)</option>
                </select>
            </div>
            <div class="form-group input-group input-group-sm">
                <div class="input-group-prepend">
                    <div class="input-group-text text-monospace font-weight-bold">3rd </div>
                </div>
                <select id="boat-pref-3" name="boatPref3" class="form-control admin-boat-preferences">
                    <option value="none" <?php if(isset($reservation['boatPref3']) && $reservation['boatPref3'] == 'none'): ?>selected<?php endif ?>>No preference</option>
                    <option value="oo2-upper" <?php if(isset($reservation['boatPref3']) && $reservation['boatPref3'] == 'oo2-upper'): ?>selected<?php endif ?>>OO2 Upper Deck (Ocean)</option>
                    <option value="oo2" <?php if(isset($reservation['boatPref3']) && $reservation['boatPref3'] == 'oo2'): ?>selected<?php endif ?>>OO2 Lower Deck (Ocean)</option>
                    <option value="tnt1" <?php if(isset($reservation['boatPref3']) && $reservation['boatPref3'] == 'tnt1'): ?>selected<?php endif ?>>TNT1 (Ocean)</option>
                    <option value="tnt2" <?php if(isset($reservation['boatPref3']) && $reservation['boatPref3'] == 'tnt2'): ?>selected<?php endif ?>>TNT2 (River)</option>
                </select>
            </div>
        </div>
    </div>
    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <button class="button btn btn-warning float-right btn-lg" type="submit">Update Boat Preferences &raquo;</button><br>
        </div>
    </div>
    <?php endif ?>
    </form>
        <fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Raw Reservation Data</legend></fieldset>
        <?php var_dump($reservation); ?>
    </div>
</div>
