<h2 class="text-center starfleet-font mx-3">Hello Admin!</h2>

<div class="container">

<?php if(isset($_GET['resent'])): ?>
<div class="alert alert-info alert-dismissible fade show text-center" role="alert">
  Confirmation email resent for reservation <strong><?= $_GET['resent'] ?></strong>.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<?php endif ?>

<?php include __DIR__ . '/menu.phtml' ?>

<form action="/admin/reservation" method="post" class="justify-content-center" id="jump-to-reservation-form">
    <fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">View Reservation</legend></fieldset>
    <div class="form-group form-row justify-content-center">
        <div class="form-check col-sm-6 col-md-5 col-lg-4">
            <input type="text" id="confirmation-code" name="confirmation-code" class="form-control form-control-lg uppercase text-center" placeholder="Confirmation code" required>
        </div>
        <div class="form-check col-sm-6 col-md-4 col-lg-3">
            <button class="button btn btn-warning float-right btn-lg" type="submit">View Reservation &raquo;</button>
        </div>
    </div>
</form>

<fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">All Reservations</legend></fieldset>

<?php
$i         = 1;
$upper     = 0;
$standard  = 0;
$private   = 0;
$tours     = 0;
$cookies   = 0;
$hats      = 0;
$stickers  = 0;
$donations = 0;
$shirtSm   = 0;
$shirtMd   = 0;
$shirtLg   = 0;
$shirtXl   = 0;
$shirt2xl  = 0;
$shirt3xl  = 0;
$tourDiscounts = 0;
$cancelled = 0;
$checkinCounts = [
    'OO2-UPPER' => 0,
    'OO2'       => 0,
    'TNT1'      => 0,
    'TNT2'      => 0,
    'SL'        => 0,
];
$assignedCounts = [
    'OO2-UPPER' => 0,
    'OO2'       => 0,
    'TNT1'      => 0,
    'TNT2'      => 0,
    'SL'        => 0,
];
$totalRevenue = 0;
?>
<table class="table table-dark w-auto mx-auto">
    <tr>
        <th>#</th>
        <th>Code</th>
        <th class="text-nowrap">Reservation Name</th>
        <th><!-- Comment Column --></th>
        <th class="hidden">Assigned Tour</th>
        <th class="text-nowrap hidden">Boat Assignment</th>
        <th class="hidden">U</th>
        <th>L</th>
        <th class="hidden">P</th>
        <th class="">T</th>
        <th class="hidden">DC</th>
        <th>C</th>
        <th class="hidden">H</th>
        <th class="hidden">SM</th>
        <th class="hidden">MD</th>
        <th class="hidden">LG</th>
        <th class="hidden">XL</th>
        <th class="hidden">2XL</th>
        <th class="hidden">3XL</th>
        <th>D</th>
        <th class="pr-4 text-nowrap">Tour Pref</th>
    </tr>
    <?php foreach ($reservations as $confirmationCode => $reservation): ?>
        <tr>
            <td><?= $i ?></td>
            <td><a href="/admin/checkin/<?= $confirmationCode ?>"><?= $confirmationCode ?></a></td>
            <td class="text-nowrap"><?php if (isset($reservation['cancelled'])): ?>🚫<? endif ?> <?= $reservation['reservationName'] ?></td>
            <?php if(isset($reservation['assignedTour'])): ?>
            <td class="hidden" <?php if(isset($reservation['tourCheckInTime'])): ?>class="alert-success"<?php endif ?>><?= $reservation['assignedTour'] ?></td>
            <?php else: ?>
            <td class="hidden"></td>
            <?php endif ?>
            <td>
            <?php if ($reservation['specialRequests']): ?>
            <button type="button" class="btn btn-secondary" data-toggle="popover" data-placement="left" data-content="<?= htmlentities($reservation['specialRequests']) ?>">
            💬
            </button>
            <?php endif ?>
            </td>
            <td class="hidden" <?php if(isset($reservation['launchCheckInTime'])): ?>class="alert-success"<?php endif ?>>
                <?php if (isset($reservation['assignedBoat'])): ?><?= $reservation['assignedBoat'] ?><?php elseif ($reservation['upperQty'] > 0): ?>OO2^<?php elseif ($reservation['privateQty'] > 0): ?>SL<?php endif ?>
                <?php if (isset($reservation['assignedBoat']) && strtolower($reservation['assignedBoat']) == $reservation['boatPref1']): ?>
                    (1<sup>st</sup>)
                <?php elseif (isset($reservation['assignedBoat']) && strtolower($reservation['assignedBoat']) == $reservation['boatPref2']): ?>
                    (2<sup>nd</sup>)
                <?php elseif (isset($reservation['assignedBoat']) && strtolower($reservation['assignedBoat']) == $reservation['boatPref3']): ?>
                    (3<sup>rd</sup>)
                <?php else: ?>
                    (N/A)
                <?php endif ?>
            </td>
            <td class="hidden"><?= $reservation['upperQty'] ?></td>
            <td class="text-nowrap <?php if(isset($reservation['launchCheckInTime']) && $reservation['standardQty'] > 0): ?>alert-success<?php endif ?>"><small>🚀</small> <?= $reservation['standardQty'] ?></td>
            <td class="text-nowrap hidden <?php if(isset($reservation['launchCheckInTime']) && $reservation['privateQty'] > 0): ?>alert-success<?php endif ?>"><small>🚀</small> <?= $reservation['privateQty'] ?></td>
            <td class="text-nowrap <?php if(isset($reservation['tourCheckInTime'])): ?>alert-success<?php endif ?>"><small>🛥️</small> <?= $reservation['tourQty'] ?></td>
            <td class="text-nowrap hidden"><?= $reservation['stickerQty'] ?></td>
            <td class="text-nowrap"><small>🍪</small> <?= $reservation['cookieQty'] ?></td>
            <td class="text-nowrap hidden"><small>🧢</small> <?= $reservation['hatQty'] ?></td>
            <td class="text-nowrap hidden"><small><small><small><small><small>👕</small></small></small></small></small> <?= $reservation['shirtQtySm'] ?></td>
            <td class="text-nowrap hidden"><small><small><small><small>👕</small></small></small></small> <?= $reservation['shirtQtyMd'] ?></td>
            <td class="text-nowrap hidden"><small><small><small>👕</small></small></small> <?= $reservation['shirtQtyLg'] ?></td>
            <td class="text-nowrap hidden"><small><small>👕</small></small> <?= $reservation['shirtQtyXl'] ?></td>
            <td class="text-nowrap hidden"><small>👕</small> <?= $reservation['shirtQty2xl'] ?></td>
            <td class="text-nowrap hidden">👕 <?= $reservation['shirtQty3xl'] ?></td>
            <td class=text-nowrap"><small>💸</small> <?= number_format($reservation['donation'],2) ?></td>
            <td class="text-nowrap">
                <?php if ($reservation['tourQty'] > 0): ?>
                <small>
                    <?php if ($reservation['tourPref1'] == 'first' && $reservation['tourPref2'] == 'second'): ?>
                    2:00pm &gt; 4:30pm
                    <?php elseif ($reservation['tourPref1'] == 'second' && $reservation['tourPref2'] == 'first'): ?>
                    4:30pm &gt; 2:00pm
                    <?php elseif ($reservation['tourPref1'] == 'none' && $reservation['tourPref2'] !='none'): ?>
                    4:30pm only
                    <?php elseif ($reservation['tourPref2'] == 'none' && $reservation['tourPref1'] !='none'): ?>
                    2:00pm only
                    <?php elseif ($reservation['tourPref1'] == 'none'): ?>
                    wtf???
                    <?php endif ?>
                </small><br>
                <?php endif ?>
                <?php /* if ($reservation['standardQty'] > 0): ?>
                <small><?= $reservation['boatPref1'] ?> &gt; <?= $reservation['boatPref2'] ?> &gt; <?= $reservation['boatPref3'] ?></small>
                <?php endif */ ?>
            </td>
        </tr>
        <?php
            $i++;
            if (isset($reservation['cancelled'])) {
                $cancelled += $reservation['standardQty'];
                continue; // don't sum up cancelled
            }
            $totalRevenue += $reservation['totalPaymentDue'];
            $upper += $reservation['upperQty'];
            $standard += $reservation['standardQty'];
            $private += $reservation['privateQty'];
            $tours += $reservation['tourQty'];
            $cookies += $reservation['cookieQty'];
            $hats += $reservation['hatQty'];
            $stickers += $reservation['stickerQty'];
            $donations += $reservation['donation'];
            $shirtSm += $reservation['shirtQtySm'];
            $shirtMd += $reservation['shirtQtyMd'];
            $shirtLg += $reservation['shirtQtyLg'];
            $shirtXl += $reservation['shirtQtyXl'];
            $shirt2xl += $reservation['shirtQty2xl'];
            $shirt3xl += $reservation['shirtQty3xl'];
            $tourDiscounts += $reservation['tourDiscountQty'];
            if (isset($reservation['assignedBoat'])) {
                $assignedCounts[$reservation['assignedBoat']]+=$reservation['standardQty'];
            }
            if (isset($reservation['launchCheckInTime']) && isset($reservation['assignedBoat'])) {
                $checkinCounts[$reservation['assignedBoat']]+=$reservation['standardQty'];
            }
        ?>
    <?php endforeach; ?>
    <tr>
        <th>#</th>
        <th>Code</th>
        <th>Reservation&nbsp;Name</th>
        <th><!-- Comment Column --></th>
        <th class="hidden">Assigned Tour</th>
        <th class="hidden">Boat Assignment</th>
        <th class="hidden">U</th>
        <th>L</th>
        <th class="hidden">P</th>
        <th class="">T</th>
        <th class="hidden">DC</th>
        <th>C</th>
        <th class="hidden">H</th>
        <th class="hidden">SM</th>
        <th class="hidden">MD</th>
        <th class="hidden">LG</th>
        <th class="hidden">XL</th>
        <th class="hidden">2XL</th>
        <th class="hidden">3XL</th>
        <th>D</th>
        <th class="pr-4">Tour Pref</th>
    </tr>
</table>

<fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Totals</legend></fieldset>
<table class="table table-dark w-auto mx-auto">
    <tr class="hidden">
        <th>Upper Tickets</th>
        <td><?= $upper ?> of <?= $upper + $inventory['upper'] ?></td>
    </tr>
    <tr>
        <th>Standard Tickets</th>
        <td><?= $standard ?> of <?= $standard + $inventory['standard'] ?></td>
    </tr>
    <tr class="hidden">
        <th>Private Tickets</th>
        <td><?= $private ?> of <?= $private + $inventory['private'] ?></td>
    </tr>
    <tr class="">
        <th>Tour Tickets</th>
        <td><?= $tours ?> of <?= $tours + $inventory['tour'] ?></td>
    </tr>
    <tr class="">
        <th>Tour+Launch Discounts</th>
        <td><?= $tourDiscounts ?></td>
    </tr>
    <tr>
        <th>Donations</th>
        <td>$<?= number_format($donations,2) ?></td>
    </tr>
    <tr class="hidden">
        <th>Decals</th>
        <td><?= $stickers ?></td>
    </tr>
    <tr>
        <th>Cookies</th>
        <td><?= $cookies ?></td>
    </tr>
    <tr class="hidden">
        <th>Hats</th>
        <td><?= $hats ?></td>
    </tr>
    <tr class="hidden">
        <th>SM Shirts</th>
        <td><?= $shirtSm ?></td>
    </tr>
    <tr class="hidden">
        <th>MD Shirts</th>
        <td><?= $shirtMd ?></td>
    </tr>
    <tr class="hidden">
        <th>LG Shirts</th>
        <td><?= $shirtLg ?></td>
    </tr>
    <tr class="hidden">
        <th>XL Shirts</th>
        <td><?= $shirtXl ?></td>
    </tr>
    <tr class="hidden">
        <th>XXL Shirts</th>
        <td><?= $shirt2xl ?></td>
    </tr>
    <tr class="hidden">
        <th>XXXL Shirts</th>
        <td><?= $shirt3xl ?></td>
    </tr>
    <tr class="hidden">
        <th>OO2 Upper Checked In</th>
        <td><?= $checkinCounts['OO2-UPPER'] ?> of <?= $assignedCounts['OO2-UPPER'] ?></td>
    </tr>
    <tr class="hidden">
        <th>OO2 Lower Checked In</th>
        <td><?= $checkinCounts['OO2'] ?> of <?= $assignedCounts['OO2'] ?></td>
    </tr>
    <tr class="hidden">
        <th>TNT1 Checked In</th>
        <td><?= $checkinCounts['TNT1'] ?> of <?= $assignedCounts['TNT1'] ?></td>
    </tr>
    <tr class="hidden">
        <th>TNT2 Checked In</th>
        <td><?= $checkinCounts['tnt2'] ?></td>
    </tr>
    <tr class="hidden">
        <th>SL Checked In</th>
        <td><?= $checkinCounts['sl'] ?></td>
    </tr>
    <tr>
        <th>Total Paid</th>
        <td>$<?= number_format($totalRevenue,2) ?></td>
    </tr>
    </table>
</div>
<script type="text/javascript">
afterJQ.push(function() {
    $('[data-toggle="popover"]').popover();
});
</script>
