<h2 class="text-center starfleet-font mx-3">Hello Admin!</h2>

<div class="container">

<?php if(isset($_GET['resent'])): ?>
<div class="alert alert-info alert-dismissible fade show text-center" role="alert">
  Confirmation email resent for reservation <strong><?= $_GET['resent'] ?></strong>.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<?php endif ?>

<div class="text-center">
<a href="/admin/discounts">Manage Discounts</a><br>
<a href="/admin/logout">[Logout]</a><br>
</div>


<form action="/admin/reservation" method="post" class="justify-content-center" id="jump-to-reservation-form">
    <fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">View Reservation</legend></fieldset>
    <div class="form-group form-row justify-content-center">
        <div class="form-check col-sm-6 col-md-5 col-lg-4">
            <input type="text" id="confirmation-code" name="confirmation-code" class="form-control form-control-lg uppercase text-center" placeholder="Confirmation code" required>
        </div>
        <div class="form-check col-sm-6 col-md-4 col-lg-3">
            <button class="button btn btn-warning float-right btn-lg" type="submit">View Reservation &raquo;</button>
        </div>
    </div>
</form>

<fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">All Reservations</legend></fieldset>

<?php
$i         = 1;
$upper     = 0;
$standard  = 0;
$private   = 0;
$tours     = 0;
$cookies   = 0;
$donations = 0;
?>
<table class="table table-dark">
    <tr>
        <th>#</th>
        <th>Code</th>
        <th>Reservation Name</th>
        <th>U</th>
        <th>S</th>
        <th>P</th>
        <th>T</th>
        <th>C</th>
        <th>D</th>
    </tr>
    <?php foreach ($reservations as $confirmationCode => $reservation): ?>
        <tr>
            <td><?= $i ?></td>
            <td><a href="/admin/checkin/<?= $confirmationCode ?>"><?= $confirmationCode ?></a></td>
            <td><?= $reservation['reservationName'] ?></td>
            <td><?= $reservation['upperQty'] ?></td>
            <td><?= $reservation['standardQty'] ?></td>
            <td><?= $reservation['privateQty'] ?></td>
            <td><?= $reservation['tourQty'] ?></td>
            <td><?= $reservation['cookieQty'] ?></td>
            <td><?= $reservation['donation'] ?></td>
        </tr>
        <?php
            $i++;
            $upper += $reservation['upperQty'];
            $standard += $reservation['standardQty'];
            $private += $reservation['privateQty'];
            $tours += $reservation['tourQty'];
            $cookies += $reservation['cookieQty'];
            $donations += $reservation['donation'];
        ?>
    <?php endforeach; ?>
    <tr>
        <th></th>
        <th></th>
        <th>Totals</th>
        <th><?= $upper ?></th>
        <th><?= $standard ?></th>
        <th><?= $private ?></th>
        <th><?= $tours ?></th>
        <th><?= $cookies ?></th>
        <th>$<?= number_format($donations,2) ?></th>
    </tr>
</table>

</div>
