<?php include __DIR__ . '/menu.phtml' ?>

<form action="/admin/inventory" method="post" class="container justify-content-center" id="inventory-form">
    <fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Manage Ticket Inventory</legend></fieldset>
    <div class="form-group form-row justify-content-center">
        <label for="upper-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Upper Deck:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="upper-qty-update" name="upperQty" min="0" step="1" value="<?= $inventory['upper'] ?>" pattern="[0-9]*" class="ticket form-control form-control-lg text-center">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
        </div>
    </div>
    <div class="form-group form-row justify-content-center">
        <label for="standard-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Standard:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="standard-qty-update" name="standardQty" min="0" step="1" value="<?= $inventory['standard'] ?>" pattern="[0-9]*" class="ticket form-control form-control-lg text-center">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
        </div>
    </div>
    <div class="form-group form-row justify-content-center">
        <label for="private-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Private:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="private-qty-update" name="privateQty" min="0" step="1" value="<?= $inventory['private'] ?>" pattern="[0-9]*" class="ticket form-control form-control-lg text-center">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
        </div>
    </div>
    <div class="form-group form-row justify-content-center">
        <label for="tour-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Tour:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="tour-qty-update" name="tourQty" min="0" step="1" value="<?= $inventory['tour'] ?>" pattern="[0-9]*" class="ticket form-control form-control-lg text-center">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
        </div>
    </div>
    <div class="form-group form-row justify-content-center">
        <label for="retry1-study" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Standard Retry:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="retry1-qty-update" name="retry1Qty" min="0" step="1" value="<?= $inventory['retry1'] ?>" pattern="[0-9]*" class="ticket form-control form-control-lg text-center">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
        </div>
    </div>

    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <button class="button btn btn-warning float-right btn-lg" type="submit">Update Inventory &raquo;</button><br>
        </div>
    </div>
</form>
