<h2 class="text-center starfleet-font mx-3">Admin Login</h2>

<form action="/admin/login" method="post" class="container justify-content-center">
    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <input type="password" name="password" class="form-control text-center">
        </div>
    </div>
    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <button class="button btn btn-warning float-right btn-lg" type="submit">Login &raquo;</button>
        </div>
    </div>
</form>
