<div class="alt-bg-section">
<h2 class="text-center starfleet-font mx-3">Join us for the SpaceX NASA Crew-2 Launch!</h2>

<form action="/review" method="post" class="container justify-content-center" id="launch-form">

<? if (isset($_GET['update'])): ?>
<div class="alert alert-info text-center" role="alert">
    You are adding items to your existing reservation, <strong><a href="/reservation/<?= $id ?>"><?= $id ?></a></strong>.
</div>
<input type="hidden" name="updateReservation" value="<?= $id ?>">
<? endif ?>
<? if (isset($_GET['soldOut'])): ?>
    <div class="alert alert-danger text-center" role="alert">
        <b>Sorry!</b> Someone already reserved those tickets while you were ordering. Please try again.
    </div>
<? endif ?>
<? if (isset($_GET['paymentError'])): ?>
    <div class="alert alert-danger text-center" role="alert">
        <b>Sorry!</b> There was a problem processing your payment. Please try again.
    </div>
<? endif ?>
<? if (isset($discountCode)): ?>
    <div class="alert alert-success text-center" role="alert">
    <b>Discount code "<?= $discountCode ?>" activated!</b> You will see your $<?= $discount['amount'] ?> discount applied on the next page.
    </div>
    <input type="hidden" name="discountCode" value="<?= $discountCode ?>">
<? endif ?>


<?php if (!isset($_GET['update'])): ?>
<fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Launch</legend>
    <div class="form-group form-row justify-content-center hidden">
        <label for="upper-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Upper Deck Launch Tickets:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="upper-qty" name="upperQty" data-price="<?= $prices['upper'] ?>" min="0" max="<?= $inventory['upper'] ?>" step="1" value="0" pattern="[0-9]*" class="ticket price-calc form-control form-control-lg text-center" aria-describedby="upper-qty-hint">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
            <span id="upper-qty-hint" class="form-text text-center">$<?= $prices['upper'] ?> per person (<?= $inventory['upper'] ?> remaining)</span>
        </div>
    </div>
    <input type="hidden" id="private-qty" name="privateQty" value="0">
    <div class="form-group form-row justify-content-center">
        <label for="standard-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Standard Launch Tickets:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="standard-qty" name="standardQty" data-price="<?= $prices['standard'] ?>" min="0" max="<?= $inventory['standard'] ?>" step="1" value="0" pattern="[0-9]*" class="ticket price-calc form-control form-control-lg text-center" aria-describedby="standard-qty-hint">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
            <span id="standard-qty-hint" class="form-text text-center">$<?= $prices['standard']; ?> per person (<?= $inventory['standard'] ?> remaining)</span>
        </div>
    </div>

    <div class="form-group form-row justify-content-center hidden">
        <p>There is no boat selection available for this launch.</p>
        <input type="hidden" name="boatPref1" value="TNT1" />
        <input type="hidden" name="boatPref2" value="none" />
    </div>


	<!--
    <div class="form-group form-row justify-content-center">
        <label for="small-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Private Boat Launch Tickets:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="private-qty" name="privateQty" data-price="<?= $prices['private']; ?>" min="0" max="<?= $inventory['private'] ?>" step="1" value="0" pattern="[0-9]*" class="ticket price-calc form-control form-control-lg text-center" aria-describedby="private-qty-hint">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
            <span id="private-qty-hint" class="form-text text-center">$<?= $prices['private']; ?> per person (<?= $inventory['private'] ?> remaining)</span>
        </div>
    </div>
	-->

    <div class="form-group form-row justify-content-center">
        <label for="tour-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Pre-Launch Tour Tickets:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="tour-qty" name="tourQty" data-price="<?= $prices['tour']; ?>" min="0" max="<?= $inventory['tour'] ?>" step="1" value="0" pattern="[0-9]*" class="ticket price-calc form-control form-control-lg text-center" aria-describedby="tour-qty-hint">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
            <span id="tour-qty-hint" class="form-text text-center">$<?= $prices['tour']; ?> per person (<?= $inventory['tour'] ?> remaining)</span>

            <div class="alert alert-success hidden text-center mt-1" role="alert" id="discount-text"></div>
        </div>
    </div>

</fieldset>

<?php endif ?>



<fieldset class="border-top border-warning rounded p-2 my-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Swag</legend>
    <div class="form-group form-row justify-content-center mt-3">
        <label for="sticker-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">
            Additional Star<span class="themed-text">✦</span>Fleet Decal(s):<br>

            <img src="/star-fleet-logo-stickers.jpg" style="max-width: 250px;" class="mt-3">
        </label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="sticker-qty" name="stickerQty" data-price="<?= $prices['sticker']; ?>" min="0" step="1" value="0" pattern="[0-9]*" class="price-calc form-control form-control-lg text-center" aria-describedby="sticker-qty-hint">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
            <span id="sticker-qty-hint" class="form-text text-center">$<?= $prices['sticker']; ?> each</span>
        </div>
    </div>
    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <span id="sticker-qty-hint2" class="form-text"><b>Note:</b> Each reservation includes one free Star<span class="themed-text">✦</span>Fleet decal, but you're welcome to purchase more!</span>
        </div>
    </div>

<hr>
    <div class="form-group form-row justify-content-center mt-3">
        <label for="cookie-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Traditional Launch Day Cookie:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="cookie-qty" name="cookieQty" data-price="<?= $prices['cookie']; ?>" min="0" step="1" value="0" pattern="[0-9]*" class="price-calc form-control form-control-lg text-center" aria-describedby="cookie-qty-hint">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
            <span id="cookie-qty-hint" class="form-text text-center">$<?= $prices['cookie']; ?> each</span>
        </div>
    </div>
    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <span id="sticker-qty-hint2" class="form-text"><b>Note:</b> One free included with each pre-launch tour ticket; otherwise $2 donation to <a href="https://www.gofundme.com/f/waywards-mission-to-beat-cancer" target="_blank">Wayward's Mission to Beat Cancer</a>.</span><br>
            <span id="cookie-qty-hint2" class="form-text">Original NASA recipe dating back to Apollo. Each individually-wrapped cookie includes a card with a note on its history and original recipe,  so you can make your own at home and carry on the tradition. Baked by Julia Bergeron in the same batch as the cookies for the actual SpaceX launch team. All proceeds go directly to <a href="https://www.gofundme.com/f/waywards-mission-to-beat-cancer" target="_blank">Wayward's Mission to Beat Cancer</a>.</span>
        </div>
    </div>

</fieldset>


<fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Gratuity</legend>
    <div class="form-group form-row justify-content-center">
        <label for="small-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Tip (Optional):</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><span class="input-group-text">$</span></div>
                <input type="number" id="donation" name="donation" min="0.00" step="0.01" value="0.00" pattern="[0-9]*" class="monetary form-control form-control-lg" aria-describedby="dontaion-hint">

                <div class="input-group-append"><span class="input-group-text alert-success">Thank you!</span></div>
            </div>
        </div>
    </div>

    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <span id="donation-hint" class="form-text">We'd like to dedicate this mission to our longtime supporter and spaceflight community stalwart Wayward Plane. Wayward was one of the very first members of the spaceflight community to back Star<span class="themed-text">✦</span>Fleet, and has been an invaluable supporter, volunteer and friend to us ever since. In lieu of our normal tip, we'll donate the full amount you specify above directly to <a href="https://www.gofundme.com/f/waywards-mission-to-beat-cancer" target="_blank">Wayward's Mission to Beat Cancer</a>, and you're also welcome to donate to the gofundme campaign directly. We hope you'll join us in giving back to someone who's given their all to help hundreds of launch viewers and space enthusiasts through Twitter, Launch Rats and much more. #Wayward4Life!</span>
        </div>
    </div>
</fieldset>

<?php if (!isset($_GET['update'])): ?>

<fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Details</legend>
    <div class="form-group form-row justify-content-center">
        <label for="reservation-name" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Name for Reservation:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <input type="text" id="reservation-name" name="reservationName" class="form-control form-control-lg" aria-describedby="reservation-name-hint" required>
            <span id="reservation-name-hint" class="form-text text-center">First, full, or group/party name.</span>
        </div>
    </div>

    <div class="form-group form-row justify-content-center">
        <label for="reservation-email" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Email Address:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <input type="email" id="reservation-email" name="reservationEmail" class="form-control form-control-lg" aria-describedby="reservation-email-hint" required>
            <span id="reservation-email-hint" class="form-text text-center">Your confirmation will be sent here.</span>
        </div>
    </div>

    <div class="form-group form-row justify-content-center">
        <div class="col-9 col-sm-12 col-md-10 col-lg-8">
            <label for="special-needs" class="form-label font-weight-bold">Special Requests / Comments:</label>
            <textarea class="form-control" id="special-requests" name="specialRequests"></textarea>
        </div>
    </div>

</fieldset>

<fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Terms and Conditions</legend>

    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-12 col-md-10 col-lg-8">
            <small id="fine-print">
			<strong>COVID-19 Safety: All passengers are REQUIRED to wear a mask at ALL TIMES while onboard. NO EXCEPTIONS. Both your mouth AND your nose must be covered.</strong>
			<br><br>
			Tickets are valid for any day the mission launches, except if a scrub occurs after we leave port one hour prior to launch time (we offer a 25% discount on further attempts). Launch dates may change without warning; if you cannot make it, we may be able to offer a limited number of refunds for tickets or merchandise up to five business days in advance of the launch date, at our sole discretion. If you have any questions, please <a href="mailto:fleetcommand@star-fleet.tours">contact&nbsp;us</a> before purchasing. Thanks!
			</small>
            <div id="accept-terms-wrapper" class="my-1">
                <label class="form-check-label" for="accept-terms">
                    <input type="checkbox" id="accept-terms" class="accept-terms" name="acceptedTerms" value="yes" required>
                    &nbsp; I agree to the <a href="https://www.star-fleet.tours/details/" target="_blank">Terms, Conditions, and Refund Policy</a>.
                </label>
					<br>
                <label class="form-check-label" for="accept-mask-terms">
                    <input type="checkbox" id="accept-mask-terms" class="accept-terms" name="acceptedMaskTerms" value="yes" required>
					&nbsp; I agree that I will wear a mask at all times while aboard.
				</label>
            </div>
        </div>
    </div>
<?php endif ?>


    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <button class="button btn btn-warning float-right btn-lg" type="submit">Review &amp; Pay &raquo;</button><br>
        </div>
    </div>
</form>
</div>
