<div class="alt-bg-section">
<h2 class="text-center starfleet-font mx-3">Join us for the SpaceX NASA Crew-3 Launch!</h2>

<form action="/review" method="post" class="container justify-content-center" id="launch-form">

<? if (isset($_GET['update'])): ?>
<div class="alert alert-info text-center" role="alert">
    You are adding items to your existing reservation, <strong><a href="/reservation/<?= $id ?>"><?= $id ?></a></strong>.
</div>
<input type="hidden" name="updateReservation" value="<?= $id ?>">
<? endif ?>
<? if (isset($_GET['soldOut'])): ?>
    <div class="alert alert-danger text-center" role="alert">
        <b>Sorry!</b> Someone already reserved those tickets while you were ordering. Please try again.
    </div>
<? endif ?>
<? if (isset($_GET['paymentError'])): ?>
    <div class="alert alert-danger text-center" role="alert">
        <b>Sorry!</b> There was a problem processing your payment. Please try again.
    </div>
<? endif ?>
<? if (isset($discountCode)): ?>
    <div class="alert alert-success text-center" role="alert">
    <b>Discount code "<?= $discountCode ?>" activated!</b> You will see your $<?= $discount['amount'] ?> discount applied on the next page.
    </div>
    <input type="hidden" name="discountCode" value="<?= $discountCode ?>">
<? endif ?>


<?php if (!isset($_GET['update'])): ?>
<fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Tickets</legend>

    <input type="hidden" id="upper-qty" value="0" name="upperQty">

    <div class="form-group form-row justify-content-center">
        <label for="standard-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Launch Tickets:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="standard-qty" name="standardQty" data-price="<?= $prices['standard'] ?>" min="0" max="<?= $inventory['standard'] ?>" step="1" value="0" pattern="[0-9]*" class="ticket price-calc form-control form-control-lg text-center" aria-describedby="standard-qty-hint">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
            <span id="standard-qty-hint" class="form-text text-center">$<?= $prices['standard']; ?> per person (<?= $inventory['standard'] ?> remaining)</span>
        </div>
    </div>

    <div class="form-group form-row justify-content-center hidden">
        <p>There is no boat selection available for this launch.</p>
        <input type="hidden" name="boatPref1" value="none" />
        <input type="hidden" name="boatPref2" value="none" />
    </div>

    <input name="privateQty" value="0" type="hidden" id="private-qty">

    <div class="form-group form-row justify-content-center">
        <label for="tour-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Pre-Launch Tour Tickets:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="tour-qty" name="tourQty" data-price="<?= $prices['tour']; ?>" min="0" max="<?= $inventory['tour'] ?>" step="1" value="0" pattern="[0-9]*" class="ticket price-calc form-control form-control-lg text-center" aria-describedby="tour-qty-hint">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
            <span id="tour-qty-hint" class="form-text text-center">$<?= $prices['tour']; ?> per person (<?= $inventory['tour'] ?> remaining)</span>

            <div class="alert alert-success hidden text-center mt-1" role="alert" id="discount-text"></div>
        </div>
    </div>
    <div class="form-group form-row justify-content-center hidden">
        <label for="standard-qtyss" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Tour Preference:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="form-group input-group input-group-sm">
                <div class="input-group-prepend">
                    <div class="input-group-text text-monospace">2:00pm (Sold Out)</div>
                </div>
                <input name="tourPref1" value="none" type="hidden">
                <select id="tour-pref-1" name="tourPref1" class="form-control tour-preferences" disabled>
                    <option value="">Select preference...</option>
                    <option value="first">1st choice</option>
                    <option value="second">2nd choice</option>
                    <option value="none" selected>Unavailable</option>
                </select>
            </div>
            <div class="form-group input-group input-group-sm">
                <div class="input-group-prepend">
                    <div class="input-group-text text-monospace">4:30pm</div>
                </div>
                <input name="tourPref2" value="first" type="hidden">
                <select id="tour-pref-2" name="tourPref2" class="form-control tour-preferences" disabled>
                    <option value="">Select preference...</option>
                    <option value="first" selected>1st choice</option>
                    <option value="second">2nd choice</option>
                    <option value="none">Unavailable</option>
                </select>
            </div>
        </div>
    </div>

</fieldset>

<?php endif ?>



<fieldset class="border-top border-warning rounded p-2 my-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Extras</legend>

    <input type="hidden" name="stickerQty" id="sticker-qty" value="0">

    <div class="form-group form-row justify-content-center mt-3">
        <label for="cookie-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Traditional Launch Day Cookie:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="cookie-qty" name="cookieQty" data-price="<?= $prices['cookie']; ?>" min="0" step="1" value="0" pattern="[0-9]*" class="price-calc form-control form-control-lg text-center" aria-describedby="cookie-qty-hint">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
            <span id="cookie-qty-hint" class="form-text text-center">$<?= $prices['cookie']; ?> each</span>
        </div>
    </div>
    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <span id="cookie-qty-hint2" class="form-text">Original NASA chocolate chip recipe dating back to Apollo. Baked by Julia Bergeron in the same batch as the cookies for the actual SpaceX launch team.</span>
        </div>
    </div>

</fieldset>


<fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Gratuity</legend>
    <div class="form-group form-row justify-content-center">
        <label for="small-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Tip (Optional):</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><span class="input-group-text">$</span></div>
                <input type="number" id="donation" name="donation" min="0.00" step="0.01" value="0.00" pattern="[0-9]*" class="monetary form-control form-control-lg" aria-describedby="dontaion-hint">

                <div class="input-group-append"><span class="input-group-text alert-success">Thank you!</span></div>
            </div>
        </div>
    </div>

    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <span id="donation-hint" class="form-text">Your generous gift will go directly toward keeping Star<span class="themed-text">✦</span>Fleet sustainable, helping reduce prices for others that can't afford it, and making more awesome launch-day opportunities available for everyone in the future. Thank you for all your support that makes our work possible!</span>
        </div>
    </div>
</fieldset>

<?php if (!isset($_GET['update'])): ?>

<fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Details</legend>
    <div class="form-group form-row justify-content-center">
        <label for="reservation-name" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Name for Reservation:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <input type="text" id="reservation-name" name="reservationName" class="form-control form-control-lg" aria-describedby="reservation-name-hint" required>
            <span id="reservation-name-hint" class="form-text text-center">First, full, or group/party name.</span>
        </div>
    </div>

    <div class="form-group form-row justify-content-center">
        <label for="reservation-email" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Email Address:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <input type="email" id="reservation-email" name="reservationEmail" class="form-control form-control-lg" aria-describedby="reservation-email-hint" required>
            <span id="reservation-email-hint" class="form-text text-center">Your confirmation will be sent here.</span>
        </div>
    </div>

    <div class="form-group form-row justify-content-center">
        <div class="col-9 col-sm-12 col-md-10 col-lg-8">
            <label for="special-needs" class="form-label font-weight-bold">Special Requests / Comments:</label>
            <textarea class="form-control" id="special-requests" name="specialRequests"></textarea>
        </div>
    </div>

</fieldset>

<fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Terms and Conditions</legend>

    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-12 col-md-10 col-lg-8">
            <small id="fine-print">
			<strong>COVID-19 Safety: All passengers must understand and agree to our COVID-19 safety policy listed on the <a href="https://www.star-fleet.tours/current/" target="_blank">tickets</a> page.</strong>
			<br><br>
			Tickets are valid for any day the mission launches, except if a scrub occurs after we leave port one hour prior to launch time (we offer a 25% discount on further attempts). Launch dates may change without warning; if you cannot make it, we may be able to offer a limited number of refunds for tickets or merchandise up to five business days in advance of the launch date, at our sole discretion. If you have any questions, please <a href="mailto:fleetcommand@star-fleet.tours">contact&nbsp;us</a> before purchasing. Thanks!
			</small>
            <div id="accept-terms-wrapper" class="my-1">
                <label class="form-check-label" for="accept-terms">
                    <input type="checkbox" id="accept-terms" class="accept-terms" name="acceptedTerms" value="yes" required>
                    &nbsp; I agree to the <a href="https://www.star-fleet.tours/details/" target="_blank">Terms, Conditions, and Refund Policy</a>.
                </label>
					<br>
                <label class="form-check-label" for="accept-mask-terms">
                    <input type="checkbox" id="accept-mask-terms" class="accept-terms" name="acceptedMaskTerms" value="yes" required>
					&nbsp; I understand and agree to the COVID-19 safety policy.
				</label>
            </div>
        </div>
    </div>
<?php endif ?>


    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <button class="button btn btn-warning float-right btn-lg" type="submit">Review &amp; Pay &raquo;</button><br>
        </div>
    </div>
</form>
</div>
