<fieldset class="border-top border-warning rounded p-2 mt-4 container"><legend class="w-auto px-2 mx-auto font-weight-bold">CRS-18 ticket sales begin in...</legend></fieldset>
<h1 class="text-center starfleet-font mx-4" id="countdown" style="letter-spacing: 3px;"></h1>
<script type="text/javascript">
Number.prototype.pad = function(size) {
    var s = String(this);
    while (s.length < (size || 2)) {s = "0" + s;}
    return s;
}
afterJQ.push(function() { updateTimer(); });
var countdownTimer = setInterval(function(){ updateTimer(); }, 1000);
function updateTimer() {
    var currentTime        = new Date().getTime() / 1000;
    var futureTime         = <?= $ticketTime ?>;
    var timeRemaining      = futureTime - currentTime;
    var minute             = 60;
    var hour               = 60 * 60;
    var day                = 60 * 60 * 24;
    var dayFloor           = Math.floor(timeRemaining / day);
    var hourFloor          = Math.floor((timeRemaining - dayFloor * day) / hour);
    var minuteFloor        = Math.floor((timeRemaining - dayFloor * day - hourFloor * hour) / minute);
    var secondFloor        = Math.floor((timeRemaining - dayFloor * day - hourFloor * hour - minuteFloor * minute));
    var multidayHour       = hourFloor + (dayFloor * 24);
    var countdownCompleted = "Completed";
    if (secondFloor <= 0 && minuteFloor <= 0) {
        clearInterval(countdownTimer);
        $('#countdown').html("TICKETS ARE NOW AVAILABLE!");
        setTimeout(function() { location.reload(true); }, 1000);
    } else if (futureTime > currentTime) {
        $('#countdown').html("T-" + multidayHour.pad() + ":" + minuteFloor.pad() + ":" + secondFloor.pad());
    }
}
</script>
