<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#fda801">
    <link rel="icon" href="https://www.star-fleet.tours/static/images/favicon.png?h=d87a7e01" type="image/png">
    <title><?=$title?></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha256-YLGeXaapI0/5IgZopewRJcFXomhRMlYYjugPLSyNjTY=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway" type="text/css">
    <style>
      :root {
        --theme-fg-color: #ffffff;
        --theme-fg-alt-color: #eeeeee;
        --theme-bg-color: #19232d;
        --theme-bg-alt-color: #32414b;
        --theme-bg-accent-color: #333333;
        --theme-accent-color: #fda801;
        --theme-pipe-color: #ffd249
      }
    </style>
    <link rel="stylesheet" href="/style.css">
    <link rel="stylesheet" href="https://www.star-fleet.tours/static/css/custom-styles.css?h=e2913cb9">
</head>
<body>
<script type="text/javascript">var afterJQ = [];</script>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top justify-content-between">
        <div class="container">
            <a href="#" class="navbar-brand">Star✦Fleet Tours</a>
                <?php if (isset($totalInTopBar)): ?>
                <ul class="navbar-nav ml-auto" id="total-price">
                    <li class="nav-item active">
                    <span class="nav-link"><strong>Total:</strong> $<span id="cart-total">0.00</span></span>
                    </li>
                </ul>
                <?php endif ?>
        </div>
    </nav>
    <?=$content?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js" integrity="sha256-fTuUgtT7O2rqoImwjrhDgbXTKUwyxxujIMRIK7TbuNU=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha256-CjSoeELFOcH0/uxWu6mC/Vlrc1AARqbm/jiiImDGV3s=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lrsjng.jquery-qrcode/0.17.0/jquery-qrcode.min.js" integrity="sha256-NHUxqf2BnYavONo/K/Ktnj31962aXHg0mO436lghKyY=" crossorigin="anonymous"></script>
<script src="https://www.star-fleet.tours/static/js/custom-scripts.js?h=4f9f7092"></script>
<script src="/ui.js"></script>
<script type="text/javascript">
    for(var i = 0; i < afterJQ.length; i++) afterJQ[i](); // I know this is nasty. Don't ask.
</script>
</body>
</html>
