<style>
#qrcodeCanvas {
    background-color: #FFF;
}
.reservation-info {
    background-color: #19232d;
    border-radius: 50px;
    padding-top: 2rem;
    padding-bottom: 2rem;
}

</style>
<div class="container mt-3">

    <div class="alert alert-info text-center" role="alert">
        <strong>Your reservation is confirmed!</strong><br>If you've purchased standard ticket(s), this page will be updated with your estimated boat assignment soon.
    </div>

    <h1 class="text-center">Your confirmation code is: <?= $id ?></h1>
    <div class="text-center"><div class="p-2 mx-auto mt-4 mb-5 w-auto d-inline-block rounded" id="qrcodeCanvas"></div></div>

    <div class="reservation-info px-5">

        <p>Thanks for your reservation to join Star<span class="themed-text">✦</span>Fleet Tours for the Falcon Heavy STP-2 launch. We look forward to seeing you there! We will scan the above QR code (printed or on your phone) to check you in on launch day, so you don't need to do anything with it now. We've sent you a confirmation email with this same information; please check your spam or junk folder to make sure it didn't end up in there.</p>

        <p>Please carefully review our <a href="https://www.star-fleet.tours/details/" target="_blank">details</a> page for important info and tips on making the most of your launch experience. We'll post status updates and any changes to the launch date and our own plans on our <a href="https://www.star-fleet.tours/current/" target="_blank">current launch page</a>, as well as on our <a href="https://twitter.com/StarFleetTours" target="_blank">Twitter feed</a>, <a href="https://www.facebook.com/starfleettours/" target="_blank">Facebook page</a>, and <a href="https://join.slack.com/t/spacexmeetups/shared_invite/enQtMzE0MjY1MTY0Mzc1LTFlMGE4MjY1ZTI4ZjZlNWQ4ZWQzZjEwMGFhNDU3NGRhZjBmNThhNTMwNzc0OWZhZGZhNzQ0YjJjNTY1Y2Q2ZWY" target="_blank">Slack group</a>. As the launch approaches, please check those frequently to stay up to date.</p>

        <p>If you have questions, concerns, or would otherwise like to get in touch with us, you can reach us on the aforementioned Slack or our <a href="https://gitter.im/star-fleet-tours/public" target="_blank">Gitter</a>, and we can also be reached by email at <a href="mailto:fleetcommand@star-fleet.tours" target="_blank">FleetCommand@Star-Fleet.Tours</a>.</p>

        <p>Thanks, and we can't wait for you to join us for the launch!</p>

    </div>
    <fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Your Reservation</legend></fieldset>

    <div class="row">
        <div class="col-lg-8">
            <table class="table table-dark">
              <thead>
                <tr>
                  <th scope="col">Description</th>
                  <th scope="col" class="text-right">Price</th>
                  <th scope="col" class="text-right">Qty</th>
                  <th scope="col" class="text-right">Total</th>
                </tr>
              <thead>
              <tbody>
                <?php if ($reservation['upperQty'] > 0): ?>
                <tr>
                  <td>Upper Deck Launch Ticket</td>
                  <td class="text-right">$<?= number_format($reservation['upperPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['upperQty'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['upperPrice'] * $reservation['upperQty'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['standardQty'] > 0): ?>
                <tr>
                  <td>Standard Launch Ticket<br><small>(Boat preference: <?= strtoupper($reservation['boatPref1']); ?>)</small></td>
                  <td class="text-right">$<?= number_format($reservation['standardPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['standardQty'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['standardPrice'] * $reservation['standardQty'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['privateQty'] > 0): ?>
                <tr>
                  <td>Private Boat Launch Ticket</td>
                  <td class="text-right">$<?= number_format($reservation['privatePrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['privateQty'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['privatePrice'] * $reservation['privateQty'],2) ?></td>
                </tr>
                <?php endif; ?>

                <?php if ($reservation['tourQty'] > 0): ?>
                <tr>
                  <td>Pre-Launch Tour<br><small>(9am - <?= $reservation['tourPref1'] == 'none' ? 'n/a' : $reservation['tourPref1'] . ' choice' ?>; 12pm - <?= $reservation['tourPref2'] == 'none' ? 'N/A' : $reservation['tourPref2'] . ' choice' ?>; 5pm - <?= $reservation['tourPref3'] == 'none' ? 'N/A' : $reservation['tourPref3'] . ' choice' ?>)</small></td>
                  <td class="text-right">$<?= number_format($reservation['tourPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['tourQty'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['tourPrice'] * $reservation['tourQty'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['shirtQtySm'] > 0): ?>
                <tr>
                  <td>Mission T-Shirt (Small)</td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['shirtQtySm'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'] * $reservation['shirtQtySm'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['shirtQtyMd'] > 0): ?>
                <tr>
                  <td>Mission T-Shirt (Medium)</td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['shirtQtyMd'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'] * $reservation['shirtQtyMd'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['shirtQtyLg'] > 0): ?>
                <tr>
                  <td>Mission T-Shirt (Large)</td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['shirtQtyLg'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'] * $reservation['shirtQtyLg'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['shirtQtyXl'] > 0): ?>
                <tr>
                  <td>Mission T-Shirt (XL)</td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['shirtQtyXl'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'] * $reservation['shirtQtyXl'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['shirtQty2xl'] > 0): ?>
                <tr>
                  <td>Mission T-Shirt (2XL)</td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['shirtQty2xl'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'] * $reservation['shirtQty2xl'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['shirtQty3xl'] > 0): ?>
                <tr>
                  <td>Mission T-Shirt (3XL)</td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['shirtQty3xl'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['shirtPrice'] * $reservation['shirtQty3xl'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['cookieQty'] > 0): ?>
                <tr>
                  <td>Traditional Launch Day Cookie</td>
                  <td class="text-right">$<?= number_format($reservation['cookiePrice'],2) ?>/ea</td>
                  <td class="text-right"><?= $reservation['cookieQty'] ?></td>
                  <td class="text-right">$<?= number_format($reservation['cookiePrice'] * $reservation['cookieQty'],2) ?></td>
                </tr>
                <?php endif; ?>
              </tbody>
            </table>
        </div><!--/col-->
        <div class="col-lg-4">
            <table class="table table-dark table-borderless">
              <thead>
                <tr>
                  <th scope="col">Subtotal</th>
                  <td scope="col" class="text-right">$<?= number_format($reservation['subTotal'],2) ?></td>
                </tr>
              <thead>
              <tbody>
                <?php if ($reservation['tourDiscountQty'] > 0): ?>
                <tr>
                  <td>Tour + Launch Discount</td>
                  <td class="text-right">-$<?= number_format($reservation['tourDiscountValue'] * $reservation['tourDiscountQty'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if (isset($reservation['discountCode'])): ?>
                <tr>
                  <td>Discount Code "<?= $reservation['discountCode'] ?>"</td>
                  <td class="text-right">-$<?= number_format($reservation['discountCodeAmount'],2) ?></td>
                </tr>
                <?php endif; ?>
                <?php if ($reservation['donation'] > 0): ?>
                <tr>
                  <td>Donation</td>
                  <td class="text-right">$<?= number_format($reservation['donation'],2) ?></td>
                </tr>
                <?php endif; ?>
                <tr class="border-top border-secondary">
                  <th scope="col">Total Paid</th>
                  <td class="text-right">$<?= number_format($reservation['totalPaymentDue'],2) ?></td>
                </tr>
              </tbody>
            </table>
        </div> <!--/col-->
    </div> <!--/row-->

</div>
<script type="text/javascript">
afterJQ.push(function() {
    $('#qrcodeCanvas').qrcode({
        render: "image",
        text: "https://book.star-fleet.tours/admin/checkin/<?= $id ?>"
    });
});
</script>
