<div class="alt-bg-section">
<h2 class="text-center starfleet-font mx-3">Join us for STP-2!</h2>

<form action="/review" method="post" class="container justify-content-center" id="launch-form">

<? if (isset($_GET['update'])): ?>
<div class="alert alert-info text-center" role="alert">
    You are adding items to your existing reservation, <strong><a href="/reservation/<?= $id ?>"><?= $id ?></a></strong>.
</div>
<input type="hidden" name="updateReservation" value="<?= $id ?>">
<? endif ?>
<? if (isset($_GET['soldOut'])): ?>
    <div class="alert alert-danger text-center" role="alert">
        <b>Sorry!</b> Someone already reserved those tickets while you were ordering. Please try again.
    </div>
<? endif ?>
<? if (isset($_GET['paymentError'])): ?>
    <div class="alert alert-danger text-center" role="alert">
        <b>Sorry!</b> There was a problem processing your payment. Please try again.
    </div>
<? endif ?>
<? if (isset($discountCode) && !isset($_GET['update'])): ?>
    <div class="alert alert-success text-center" role="alert">
    <b>Discount code "<?= $discountCode ?>" activated!</b> You will see your $<?= $discount['amount'] ?> discount applied on the next page.
    </div>
    <input type="hidden" name="discountCode" value="<?= $discountCode ?>">
<? endif ?>


<?php if (!isset($_GET['update'])): ?>
<fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Launch</legend>
    <div class="form-group form-row justify-content-center">
        <label for="upper-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Upper Deck Launch Tickets:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="upper-qty" name="upperQty" data-price="<?= $prices['upper'] ?>" min="0" max="<?= $inventory['upper'] ?>" step="1" value="0" pattern="[0-9]*" class="ticket price-calc form-control form-control-lg text-center" aria-describedby="upper-qty-hint">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
            <span id="upper-qty-hint" class="form-text text-center">$<?= $prices['upper'] ?> per person (<?= $inventory['upper'] ?> remaining)</span>
        </div>
    </div>

    <div class="form-group form-row justify-content-center">
        <label for="standard-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Standard Launch Tickets:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="standard-qty" name="standardQty" data-price="<?= $prices['standard'] ?>" min="0" max="<?= $inventory['standard'] ?>" step="1" value="0" pattern="[0-9]*" class="ticket price-calc form-control form-control-lg text-center" aria-describedby="standard-qty-hint">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
            <span id="standard-qty-hint" class="form-text text-center">$<?= $prices['standard']; ?> per person (<?= $inventory['standard'] ?> remaining)</span>
        </div>
    </div>

    <div class="form-group form-row justify-content-center hidden">
        <label for="boat-pref-1" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Boat Preference:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="form-group input-group input-group-sm">
                <select id="boat-pref-1" name="boatPref1" class="form-control boat-preferences">
                    <option value="none" selected>No preference</option>
                    <option value="oo2">Ocean Obsession II</option>
                    <option value="tnt1">Time and Tide I</option>
                </select>
            </div>
        </div>
    </div>
<!--
    <div class="form-group form-row justify-content-center hidden">
        <label for="boat-pref-1" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Boat Preference:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="form-group input-group input-group-sm">
                <div class="input-group-prepend">
                    <div class="input-group-text text-monospace font-weight-bold">1st </div>
                </div>
                <select id="boat-pref-1" class="form-control boat-preferences">
                    <option value="none" selected>No preference</option>
                    <option value="oo2">OO2 (Ocean)</option>
                    <option value="tnt1">TNT1 (Ocean)</option>
                    <option value="tnt2">TNT2 (River)</option>
                </select>
            </div>
            <div class="form-group input-group input-group-sm">
                <div class="input-group-prepend">
                    <div class="input-group-text text-monospace font-weight-bold">2nd </div>
                </div>
                <select id="boat-pref-2" class="form-control boat-preferences">
                    <option value="none" selected>No preference</option>
                    <option value="oo2">OO2 (Ocean)</option>
                    <option value="tnt1">TNT1 (Ocean)</option>
                    <option value="tnt2">TNT2 (River)</option>
                </select>
            </div>
            <div class="form-group input-group input-group-sm">
                <div class="input-group-prepend">
                    <div class="input-group-text text-monospace font-weight-bold">3rd </div>
                </div>
                <select id="boat-pref-3" class="form-control boat-preferences">
                    <option value="none" selected>No preference</option>
                    <option value="oo2">OO2 (Ocean)</option>
                    <option value="tnt1">TNT1 (Ocean)</option>
                    <option value="tnt2">TNT2 (River)</option>
                </select>
            </div>
        </div>
    </div>
-->

    <div class="form-group form-row justify-content-center">
        <label for="small-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Private Boat Launch Tickets:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="private-qty" name="privateQty" data-price="<?= $prices['private']; ?>" min="0" max="<?= $inventory['private'] ?>" step="1" value="0" pattern="[0-9]*" class="ticket price-calc form-control form-control-lg text-center" aria-describedby="private-qty-hint">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
            <span id="private-qty-hint" class="form-text text-center">$<?= $prices['private']; ?> per person (<?= $inventory['private'] ?> remaining)</span>
        </div>
    </div>
</fieldset>


<fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Tour</legend>

    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <div class="alert alert-success text-center" role="alert">
              <b>Special offer!</b> $10 off for each tour AND launch ticket purchased together!
            </div>
        </div>
    </div>

    <div class="form-group form-row justify-content-center">
        <label for="tour-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Pre-Launch Tour Tickets:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="tour-qty" name="tourQty" data-price="<?= $prices['tour']; ?>" min="0" max="<?= $inventory['tour'] ?>" step="1" value="0" pattern="[0-9]*" class="ticket price-calc form-control form-control-lg text-center" aria-describedby="tour-qty-hint">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
            <span id="tour-qty-hint" class="form-text text-center">$<?= $prices['tour']; ?> per person (<?= $inventory['tour'] ?> remaining)</span>

            <div class="alert alert-success hidden text-center mt-1" role="alert" id="discount-text"></div>
        </div>
    </div>
    <div class="form-group form-row justify-content-center hidden">
        <label for="standard-qtyss" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Tour Preference:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="form-group input-group input-group-sm">
                <div class="input-group-prepend">
                    <div class="input-group-text text-monospace">8am-11:30pm</div>
                </div>
                <select id="tour-pref-1" name="tourPref1" class="form-control tour-preferences">
                    <option value="" selected>Select preference...</option>
                    <option value="first">1st choice</option>
                    <option value="second">2nd choice</option>
                    <option value="third">3rd choice</option>
                    <option value="none">Unavailable</option>
                </select>
            </div>
            <div class="form-group input-group input-group-sm">
                <div class="input-group-prepend">
                    <div class="input-group-text text-monospace">11:30am-3pm</div>
                </div>
                <select id="tour-pref-2" name="tourPref2" class="form-control tour-preferences">
                    <option value="" selected>Select preference...</option>
                    <option value="first">1st choice</option>
                    <option value="second">2nd choice</option>
                    <option value="third">3rd choice</option>
                    <option value="none">Unavailable</option>
                </select>
            </div>
            <div class="form-group input-group input-group-sm">
                <div class="input-group-prepend">
                    <div class="input-group-text text-monospace">&nbsp;3pm-6:30pm</div>
                </div>
                <select id="tour-pref-3" name="tourPref3" class="form-control tour-preferences">
                    <option value="" selected>Select preference...</option>
                    <option value="first">1st choice</option>
                    <option value="second">2nd choice</option>
                    <option value="third">3rd choice</option>
                    <option value="none">Unavailable</option>
                </select>
            </div>
            <!--<span id="standard-qty-hint" class="form-text">We'll do our best to get your party on the preferred boat.</span>-->
        </div>
    </div>
</fieldset>

<?php endif ?>


<fieldset class="border-top border-warning rounded p-2 my-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Swag</legend>

    <div class="form-group form-row justify-content-center">
        <label for="shirt-qty-sm" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold text-nowrap">
            Star<span class="themed-text">✦</span>Fleet STP-2 Patch T-Shirt:<br>
            <img src="/stp2shirt.png" style="max-width: 250px;" class="mt-3">
        </label>

        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="row justify-content-center mt-4">
                <div class="col-6">
                    <span class="form-text text-center">S</span>
                    <div class="input-group justify-content-center">
                        <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                        <input type="number" id="shirt-qty-sm" name="shirtQtySm" data-price="<?= $prices['shirt']; ?>" min="0" step="1" value="0" pattern="[0-9]*" class="price-calc form-control text-center shirt-qty" aria-describedby="shirt-qty-hint">
                        <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
                    </div>
                </div>

                <div class="col-6">
                    <span class="form-text text-center">M</span>
                    <div class="input-group justify-content-center">
                        <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                        <input type="number" id="shirt-qty-md" name="shirtQtyMd" data-price="<?= $prices['shirt']; ?>" min="0" step="1" value="0" pattern="[0-9]*" class="price-calc form-control text-center shirt-qty" aria-describedby="shirt-qty-hint">
                        <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
                    </div>
                </div>

                <div class="col-6">
                    <span class="form-text text-center">L</span>
                    <div class="input-group justify-content-center">
                        <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                        <input type="number" id="shirt-qty-lg" name="shirtQtyLg" data-price="<?= $prices['shirt']; ?>" min="0" step="1" value="0" pattern="[0-9]*" class="price-calc form-control text-center shirt-qty" aria-describedby="shirt-qty-hint">
                        <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
                    </div>
                </div>

                <div class="col-6">
                    <span class="form-text text-center">XL</span>
                    <div class="input-group justify-content-center">
                        <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                        <input type="number" id="shirt-qty-xl" name="shirtQtyXl" data-price="<?= $prices['shirt']; ?>" min="0" step="1" value="0" pattern="[0-9]*" class="price-calc form-control text-center shirt-qty" aria-describedby="shirt-qty-hint">
                        <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
                    </div>
                </div>

                <div class="col-6">
                    <span class="form-text text-center">2XL</span>
                    <div class="input-group justify-content-center">
                        <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                        <input type="number" id="shirt-qty-xxl" name="shirtQty2xl" data-price="<?= $prices['shirt']; ?>" min="0" step="1" value="0" pattern="[0-9]*" class="price-calc form-control text-center shirt-qty" aria-describedby="shirt-qty-hint">
                        <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
                    </div>
                </div>

                <div class="col-6">
                    <span class="form-text text-center">3XL</span>
                    <div class="input-group justify-content-center">
                        <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                        <input type="number" id="shirt-qty-xxxl" name="shirtQty3xl" data-price="<?= $prices['shirt']; ?>" min="0" step="1" value="0" pattern="[0-9]*" class="price-calc form-control text-center shirt-qty" aria-describedby="shirt-qty-hint">
                        <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center mt-3">
                <span id="shirt-qty-hint" class="form-text text-center">All sizes $<?= $prices['shirt']; ?> each</span>
            </div>
        </div>
    </div>

    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <span id="shirt-qty-hint" class="form-text">Custom-designed T-shirt with our own Star<span class="themed-text">✦</span>Fleet Tours patch for the STP-2 mission. Will be available for pickup at boat check-in.</span>
        </div>
    </div>

    <div class="rule-under-heading mb-4"></div>

    <div class="form-group form-row justify-content-center mt-3">
        <label for="cookie-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Traditional Launch Day Cookie:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><button class="btn btn-decrement btn-secondary" type="button"><strong>-</strong></button></div>
                <input type="number" id="cookie-qty" name="cookieQty" data-price="<?= $prices['cookie']; ?>" min="0" step="1" value="0" pattern="[0-9]*" class="price-calc form-control form-control-lg text-center" aria-describedby="cookie-qty-hint">
                <div class="input-group-append"><button class="btn btn-increment btn-secondary" type="button"><strong>+</strong></button></div>
            </div>
            <span id="cookie-qty-hint" class="form-text text-center">$<?= $prices['cookie']; ?> each</span>
        </div>
    </div>
    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <span id="shirt-qty-hint" class="form-text">Original NASA recipe dating back to Apollo. Each individually-wrapped cookie includes a card with a note on its history and original recipe,  so you can make your own at home and carry on the tradition. Baked by Julia Bergeron in the same batch as the cookies for the actual SpaceX launch team for STP-2. Proceeds benefit the <a href="https://scla.space/" target="_blank">Space Coast Launch Ambassadors</a> volunteer organization. <br><br><b>Note:</b> Each pre-launch tour ticket includes one free launch day cookie, but you're welcome to reserve more!</span>
        </div>
    </div>
</fieldset>


<fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Donate</legend>
    <div class="form-group form-row justify-content-center">
        <label for="small-qty" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Donation (Optional):</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <div class="input-group">
                <div class="input-group-prepend"><span class="input-group-text">$</span></div>
                <input type="number" id="donation" name="donation" min="0.00" step="0.01" value="0.00" pattern="[0-9]*" class="monetary form-control form-control-lg" aria-describedby="dontaion-hint">

                <div class="input-group-append"><span class="input-group-text alert-success">Thank you!</span></div>
            </div>
        </div>
    </div>

    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <span id="donation-hint" class="form-text">Your generous gift will go directly toward keeping Star<span class="themed-text">✦</span>Fleet sustainable, helping reduce prices for others that can't afford it, and making more awesome launch-day opportunities available for everyone in the future. Thank you for all your support that makes our work possible!</span>
        </div>
    </div>
</fieldset>


<?php if (!isset($_GET['update'])): ?>
<fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Details</legend>
    <div class="form-group form-row justify-content-center">
        <label for="reservation-name" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Name for Reservation:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <input type="text" id="reservation-name" name="reservationName" class="form-control form-control-lg" aria-describedby="reservation-name-hint" required>
            <span id="reservation-name-hint" class="form-text text-center">First, full, or group/party name.</span>
        </div>
    </div>

    <div class="form-group form-row justify-content-center">
        <label for="reservation-email" class="col-form-label col-9 col-sm-6 col-md-5 col-lg-4 font-weight-bold">Email Address:</label>
        <div class="col-9 col-sm-6 col-md-5 col-lg-4 align-self-center">
            <input type="email" id="reservation-email" name="reservationEmail" class="form-control form-control-lg" aria-describedby="reservation-email-hint" required>
            <span id="reservation-email-hint" class="form-text text-center">Your confirmation will be sent here.</span>
        </div>
    </div>

    <div class="form-group form-row justify-content-center">
        <div class="col-9 col-sm-12 col-md-10 col-lg-8">
            <label for="special-needs" class="form-label font-weight-bold">Special Requests / Comments:</label>
            <textarea class="form-control" id="special-requests" name="specialRequests"></textarea>
        </div>
    </div>

</fieldset>

<fieldset class="border-top border-warning rounded p-2 mt-4"><legend class="w-auto px-2 ml-4 font-weight-bold">Terms and Conditions</legend>

    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-12 col-md-10 col-lg-8">
            <small id="fine-print">Tickets are valid for any day the mission launches, except if a scrub occurs after we leave port one hour prior to launch time (we offer a 33% discount on further attempts). Launch dates may change without warning; if you cannot make it, we may be able to offer a limited number of refunds for tickets or merchandise up to five business days in advance of the launch date, at our sole discretion. If you have any questions, please <a href="mailto:fleetcommand@star-fleet.tours">contact&nbsp;us</a> before purchasing. Thanks!</small>
            <div id="accept-terms-wrapper" class="my-1">
                <label class="form-check-label" for="accept-terms">
                    <input class="" type="checkbox" id="accept-terms" name="acceptedTerms" value="yes" required>
                    &nbsp; I agree to the <a href="https://www.star-fleet.tours/details/" target="_blank">Terms, Conditions, and Refund Policy</a>.
                </label>
            </div>
        </div>
    </div>
<?php endif ?>


    <div class="form-group form-row justify-content-center">
        <div class="form-check col-9 col-sm-11 col-md-10 col-lg-8">
            <button class="button btn btn-warning float-right btn-lg" type="submit">Review &amp; Pay &raquo;</button><br>
        </div>
    </div>
</form>
</div>
